apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-react-app
  labels:
    app.kubernetes.io/name: test-react-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: test-react-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-react-app
    spec:
      containers:
        - name: test-react-app
          image: "{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          resources: {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always