apiVersion: v1
kind: Service
metadata:
  name: test-react-app
  labels:
    app.kubernetes.io/name: test-react-app
spec:
  selector:
    app.kubernetes.io/name: test-react-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080